--- #YAML:1.0
name:                Acme-Stardate
version:             20081029.16083
abstract:            Provide a simple 'stardate' string
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Exporter:                      0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Chris Fedde <cfedde at cpan.org>
